server:
  port: 8001
spring:
  application:
    name: eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/${spring.application.name}/
    register-with-eureka: false
    fetch-registry: false
