server:
  port: 8020

spring:
  application:
    name: consumer-hystrix
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
feign:
  hystrix:
    enabled: true
