server:
  port: 8040

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
          #默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          enabled: true
          #通过小写访问服务
          lower-case-service-id: true
  redis:
    port: 6379
    password: password
    database: 0
    host: localhost
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
