server:
  port: 8020
spring:
  application:
    name: consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#  client:
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://localhost:8001/eureka/
