server:
  port: 8011
spring:
  application:
    name: producer
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        enabled: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8001/eureka/
appName: producer2
